[project]
name = "nuts"
version = "0.1.0"
description = "NUTS Implementation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipython>=8.38.0",
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "scipy>=1.15.3",
    "tqdm>=4.67.1",
]
